export interface SkillCategory {
  title: string;
  subtitle?: string;
  skills: string[];
}

export const skillCategories: SkillCategory[] = [
  {
    title: 'Languages',
    skills: [
      'Java',
      'Python',
      'TypeScript',
      'Rust',
      'Golang',
      'JavaScript',
      'C / C++',
      'Kotlin',
      'SQL',
      'Bash',
      'HTML5',
      'CSS3',
    ],
  },
  {
    title: 'Frontend',
    skills: [
      'React.js',
      'Next.js 15',
      'Tailwind CSS',
      'Vite',
      'Redux Toolkit',
      'Zustand',
      'Framer Motion',
      'HTML5',
      'Responsive UI',
      'CSS3',
      'React Query',
      'Shadcn UI',
    ],
  },
  {
    title: 'Backend',
    skills: [
      'Node.js',
      'Express.js',
      'Spring Boot',
      'FastAPI',
      'REST APIs',
      'GraphQL',
      'Microservices',
      'gRPC',
      'JWT Auth',
      'OAuth 2.0',
      'WebSockets',
      'Socket.io',
    ],
  },
  {
    title: 'Database & Storage',
    skills: [
      'PostgreSQL',
      'MySQL',
      'MongoDB',
      'Redis',
      'Firebase',
      'Supabase',
      'AWS DynamoDB',
      'SQLite',
      'Prisma ORM',
      'Mongoose',
      'Cloudflare R2',
      'AWS S3',
    ],
  },
  {
    title: 'Tools & DevOps',
    skills: [
      'Docker',
      'Postman',
      'Git & GitHub',
      'Nginx',
      'AWS (EC2, S3)',
      'CI/CD',
      'Kubernetes',
      'Vercel',
      'GitHub Actions',
      'Linux',
      'Cloudflare',
      'VS Code',
    ],
  },
  {
    title: 'AI / ML',
    skills: [
      'Agentic AI',
      'Gemini API',
      'LangChain',
      'OpenCV',
      'YOLOv8',
      'Scikit-learn',
      'PyTorch',
      'NVIDIA API',
      'RAG Pipelines',
      'LLMs',
      'Pandas',
      'NumPy',
    ],
  },
];

export const softSkills: string[] = [
  'Problem Solving & DSA',
  'System Thinking & Design',
  'Team Leadership (TPO Coordinator)',
  'Agile / Scrum Collaboration',
  'Technical Communication',
  'Cross-Functional Execution',
  'Event & Hackathon Coordination',
  'Adaptability & Fast Learner',
];
